const prefixs: { [index: string]: string } = {
  play: 'play',
  skip: 'skip',
  stop: 'stop',
  back: 'back',
  pause: 'pause',
  clear: 'clear',
  resume: 'resume',
  exp: 'exp',
  queue: 'queue',
  disconnect: 'disconnect',
  help: 'help',
  lyrics: 'lyrics',
  jump: 'jump',
  remove: 'remove',
  nowplaying: 'nowplaying',
  ping: 'ping',
  tg: 'tg',
};
export { prefixs };
